steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/theproductowner-8620d/azmyra-agents', '-f', 'Dockerfile.agents', '.']
images:
  - 'gcr.io/theproductowner-8620d/azmyra-agents'
